
CREATE TABLE books (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       bookname VARCHAR(64) NOT NULL,
                       author VARCHAR(128) NOT NULL,
                       quantity INT
);